id: I611168D9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T23:20:54+00:00'
last_modified: '2022-06-07T15:13:35.784460+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W16837
  title: བླུན་པོ་འདྲེས་འཁྱེར་སོགས་ལེ་ཚན་གཉིས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3A5A:
      image_group_id: I1KG10533
      title: ''
      total_pages: 12
      order: 1
      base_file: 3A5A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
