id: P001806
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W16837
  title: བླུན་པོ་འདྲེས་འཁྱེར་སོགས་ལེ་ཚན་གཉིས།
  author: ''
  volumes:
    66e3ca42e18c49a59ff0038d2404afc5:
      image_group_id: I1KG10533
      title: ''
      volume_number: 1
      total_pages: 12
      base_file: v001.txt
